discoveryservice:
  image: "com.kramkroc/discovery-service"
  hostname: discoveryservice
  name: discoveryservice
  ports:
   - "8761:8761"

configserver:
  image: "com.kramkroc/config-server"
  hostname: configserver
  name: configserver
  restart: always  
  links:
    - discoveryservice
  environment:
     EUREKA_HOST: discoveryservice
     EUREKA_PORT: 8761
  ports:
    - "8888:8888"

sampleservice:
  image: "com.kramkroc/sample-service"
  hostname: sampleservice
  name: sampleservice
  restart: always
  links:
    - discoveryservice
    - configserver
  environment:
     EUREKA_HOST: discoveryservice
     EUREKA_PORT: 8761
  ports:
    - "8082:8082"
  restart: always